function renderWorkPackage({ taskDescription, product, architecture, qa, prompt, release }) {
  return [
    `# Big Crew Engineering Work Package`,
    "",
    `## Task Summary`,
    `${taskDescription}`,
    "",
    `## Product Value`,
    `- ${product.objective}`,
    ...product.notes.map((note) => `- ${note}`),
    "",
    `## Priority`,
    `- ${product.notes[1]}`,
    `- ${product.notes[2]}`,
    "",
    `## In Scope`,
    `- ${product.notes[1]}`,
    `- ${architecture.notes[1]}`,
    "",
    `## Out of Scope`,
    `- Complex orchestration`,
    `- External AI API integration`,
    "",
    `## Architecture Impact`,
    `- ${architecture.objective}`,
    ...architecture.notes.map((note) => `- ${note}`),
    "",
    `## Acceptance Criteria`,
    `- ${qa.objective}`,
    ...qa.notes.map((note) => `- ${note}`),
    "",
    `## Regression Tests`,
    `- ${qa.notes[0]}`,
    `- ${qa.notes[1]}`,
    "",
    `## Codex-Ready Prompt`,
    `- ${prompt.objective}`,
    ...prompt.notes.map((note) => `- ${note}`),
    "",
    `## Definition of Done`,
    `- ${release.objective}`,
    ...release.notes.map((note) => `- ${note}`),
    "",
    `## Release Captain`,
    `- ${release.objective}`,
    ...release.notes.map((note) => `- ${note}`),
    "",
    `## Notes`,
    `- No external AI API is used in this MVP.`,
    `- This package is rule-based and template-based only.`,
  ].join("\n");
}

module.exports = {
  renderWorkPackage,
};
